//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class AccidentReport : XPObject
    {
        string fAccidentType;
        public string AccidentType
        {
            get { return fAccidentType; }
            set { SetPropertyValue<string>(nameof(AccidentType), ref fAccidentType, value); }
        }
        DateTime fOccurredDate;
        public DateTime OccurredDate
        {
            get { return fOccurredDate; }
            set { SetPropertyValue<DateTime>(nameof(OccurredDate), ref fOccurredDate, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fEquipments;
        public string Equipments
        {
            get { return fEquipments; }
            set { SetPropertyValue<string>(nameof(Equipments), ref fEquipments, value); }
        }
        string fOperation;
        public string Operation
        {
            get { return fOperation; }
            set { SetPropertyValue<string>(nameof(Operation), ref fOperation, value); }
        }
        Personnel fInjuredPerson;
        [Association(@"AccidentReportReferencesPersonnel")]
        public Personnel InjuredPerson
        {
            get { return fInjuredPerson; }
            set { SetPropertyValue<Personnel>(nameof(InjuredPerson), ref fInjuredPerson, value); }
        }
        string fInjuryType;
        public string InjuryType
        {
            get { return fInjuryType; }
            set { SetPropertyValue<string>(nameof(InjuryType), ref fInjuryType, value); }
        }
        string fInjuredParts;
        public string InjuredParts
        {
            get { return fInjuredParts; }
            set { SetPropertyValue<string>(nameof(InjuredParts), ref fInjuredParts, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fActions;
        [Size(SizeAttribute.Unlimited)]
        public string Actions
        {
            get { return fActions; }
            set { SetPropertyValue<string>(nameof(Actions), ref fActions, value); }
        }
        string fResult;
        [Size(SizeAttribute.Unlimited)]
        public string Result
        {
            get { return fResult; }
            set { SetPropertyValue<string>(nameof(Result), ref fResult, value); }
        }
        int fLostWorkDays;
        public int LostWorkDays
        {
            get { return fLostWorkDays; }
            set { SetPropertyValue<int>(nameof(LostWorkDays), ref fLostWorkDays, value); }
        }
        string fAccidentCauses;
        [Size(SizeAttribute.Unlimited)]
        public string AccidentCauses
        {
            get { return fAccidentCauses; }
            set { SetPropertyValue<string>(nameof(AccidentCauses), ref fAccidentCauses, value); }
        }
        string fRootCauses;
        public string RootCauses
        {
            get { return fRootCauses; }
            set { SetPropertyValue<string>(nameof(RootCauses), ref fRootCauses, value); }
        }
        string fCorrection;
        public string Correction
        {
            get { return fCorrection; }
            set { SetPropertyValue<string>(nameof(Correction), ref fCorrection, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        WellWork fWorkID;
        [Association(@"AccidentReportReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fAgent;
        [Association(@"AccidentReportReferencesUser")]
        public User Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<User>(nameof(Agent), ref fAgent, value); }
        }
    }

}
