//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Asset : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Rig fRigNo;
        [Association(@"AssetReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
        string fOwner;
        public string Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<string>(nameof(Owner), ref fOwner, value); }
        }
        string fPosition;
        public string Position
        {
            get { return fPosition; }
            set { SetPropertyValue<string>(nameof(Position), ref fPosition, value); }
        }
        string fSerial;
        public string Serial
        {
            get { return fSerial; }
            set { SetPropertyValue<string>(nameof(Serial), ref fSerial, value); }
        }
        DateTime? fExpireDate;
        public DateTime? ExpireDate
        {
            get { return fExpireDate; }
            set { SetPropertyValue<DateTime?>(nameof(ExpireDate), ref fExpireDate, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
