//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Committee : XPObject
    {
        DateTime fHoldDate;
        public DateTime HoldDate
        {
            get { return fHoldDate; }
            set { SetPropertyValue<DateTime>(nameof(HoldDate), ref fHoldDate, value); }
        }
        User fSecretaryName;
        [Association(@"CommitteeReferencesUser")]
        public User SecretaryName
        {
            get { return fSecretaryName; }
            set { SetPropertyValue<User>(nameof(SecretaryName), ref fSecretaryName, value); }
        }
        Personnel fChiefName;
        [Association(@"CommitteeReferencesChief")]
        public Personnel ChiefName
        {
            get { return fChiefName; }
            set { SetPropertyValue<Personnel>(nameof(ChiefName), ref fChiefName, value); }
        }
        WellWork fWorkID;
        [Association(@"CommitteeReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        short fSeverity;
        public short Severity
        {
            get { return fSeverity; }
            set { SetPropertyValue<short>(nameof(Severity), ref fSeverity, value); }
        }
        [Association(@"CommitteeReferencesParticipants")]
        public XPCollection<Personnel> Participants { get { return GetCollection<Personnel>(nameof(Participants)); } }
        [Association(@"CommitteeItemReferencesCommittee"), Aggregated]
        public XPCollection<CommitteeItem> CommitteeItems { get { return GetCollection<CommitteeItem>(nameof(CommitteeItems)); } }
    }

}
