//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class CommitteeItem : XPObject
    {
        Committee fCommitteeName;
        [Association(@"CommitteeItemReferencesCommittee")]
        public Committee CommitteeName
        {
            get { return fCommitteeName; }
            set { SetPropertyValue<Committee>(nameof(CommitteeName), ref fCommitteeName, value); }
        }
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        string fTrackerRole;
        public string TrackerRole
        {
            get { return fTrackerRole; }
            set { SetPropertyValue<string>(nameof(TrackerRole), ref fTrackerRole, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>(nameof(DueDate), ref fDueDate, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
