//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class DisposedMedicine : XPObject
    {
        Medication fMedicName;
        [Association(@"DisposedMedicineReferencesMedication")]
        public Medication MedicName
        {
            get { return fMedicName; }
            set { SetPropertyValue<Medication>(nameof(MedicName), ref fMedicName, value); }
        }
        DateTime fDisDate;
        public DateTime DisDate
        {
            get { return fDisDate; }
            set { SetPropertyValue<DateTime>(nameof(DisDate), ref fDisDate, value); }
        }
        string fReason;
        public string Reason
        {
            get { return fReason; }
            set { SetPropertyValue<string>(nameof(Reason), ref fReason, value); }
        }
        short fMedCount;
        public short MedCount
        {
            get { return fMedCount; }
            set { SetPropertyValue<short>(nameof(MedCount), ref fMedCount, value); }
        }
        Rig fRigNo;
        [Association(@"DisposedMedicineReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
    }

}
