//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Equipment : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCountUnit;
        public string CountUnit
        {
            get { return fCountUnit; }
            set { SetPropertyValue<string>(nameof(CountUnit), ref fCountUnit, value); }
        }
        string fModel;
        public string Model
        {
            get { return fModel; }
            set { SetPropertyValue<string>(nameof(Model), ref fModel, value); }
        }
        string fEquipType;
        public string EquipType
        {
            get { return fEquipType; }
            set { SetPropertyValue<string>(nameof(EquipType), ref fEquipType, value); }
        }
        string fWhoNeed;
        [Size(SizeAttribute.Unlimited)]
        public string WhoNeed
        {
            get { return fWhoNeed; }
            set { SetPropertyValue<string>(nameof(WhoNeed), ref fWhoNeed, value); }
        }
        [Association(@"PPEReferencesEquipment"), Aggregated]
        public XPCollection<PPE> PPEs { get { return GetCollection<PPE>(nameof(PPEs)); } }
        [Association(@"MaterialListReferencesEquipment"), Aggregated]
        public XPCollection<MaterialList> MaterialLists { get { return GetCollection<MaterialList>(nameof(MaterialLists)); } }
        [Association(@"EquipmentStockReferencesEquipment"), Aggregated]
        public XPCollection<EquipmentStock> EquipmentStocks { get { return GetCollection<EquipmentStock>(nameof(EquipmentStocks)); } }
    }

}
