//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class EquipmentStock : XPObject
    {
        Equipment fEquipmentName;
        [Association(@"EquipmentStockReferencesEquipment")]
        public Equipment EquipmentName
        {
            get { return fEquipmentName; }
            set { SetPropertyValue<Equipment>(nameof(EquipmentName), ref fEquipmentName, value); }
        }
        Rig fRigNo;
        [Association(@"EquipmentStockReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
        int fCounts;
        public int Counts
        {
            get { return fCounts; }
            set { SetPropertyValue<int>(nameof(Counts), ref fCounts, value); }
        }
    }

}
