//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class FireEquip : XPObject
    {
        Rig fRigNo;
        [Association(@"FireEquipReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fPosition;
        public string Position
        {
            get { return fPosition; }
            set { SetPropertyValue<string>(nameof(Position), ref fPosition, value); }
        }
        string fSerialNo;
        public string SerialNo
        {
            get { return fSerialNo; }
            set { SetPropertyValue<string>(nameof(SerialNo), ref fSerialNo, value); }
        }
        string fExtinguisherType;
        public string ExtinguisherType
        {
            get { return fExtinguisherType; }
            set { SetPropertyValue<string>(nameof(ExtinguisherType), ref fExtinguisherType, value); }
        }
        DateTime? fLastCheck;
        public DateTime? LastCheck
        {
            get { return fLastCheck; }
            set { SetPropertyValue<DateTime?>(nameof(LastCheck), ref fLastCheck, value); }
        }
        DateTime? fLastCharge;
        public DateTime? LastCharge
        {
            get { return fLastCharge; }
            set { SetPropertyValue<DateTime?>(nameof(LastCharge), ref fLastCharge, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
