//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class HSEForm : XPObject
    {
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        DateTime fRevDate;
        public DateTime RevDate
        {
            get { return fRevDate; }
            set { SetPropertyValue<DateTime>(nameof(RevDate), ref fRevDate, value); }
        }
        string fRevision;
        public string Revision
        {
            get { return fRevision; }
            set { SetPropertyValue<string>(nameof(Revision), ref fRevision, value); }
        }
        string fKeywords;
        public string Keywords
        {
            get { return fKeywords; }
            set { SetPropertyValue<string>(nameof(Keywords), ref fKeywords, value); }
        }
        string fFormType;
        public string FormType
        {
            get { return fFormType; }
            set { SetPropertyValue<string>(nameof(FormType), ref fFormType, value); }
        }
        byte[] fData;
        [MemberDesignTimeVisibility(true)]
        public byte[] Data
        {
            get { return fData; }
            set { SetPropertyValue<byte[]>(nameof(Data), ref fData, value); }
        }
        string fModuleCode;
        public string ModuleCode
        {
            get { return fModuleCode; }
            set { SetPropertyValue<string>(nameof(ModuleCode), ref fModuleCode, value); }
        }
        [Association(@"ReportReferencesHSEForm"), Aggregated]
        public XPCollection<Report> Reports { get { return GetCollection<Report>(nameof(Reports)); } }
    }

}
