//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class MaterialList : XPObject
    {
        Equipment fMaterialName;
        [Association(@"MaterialListReferencesEquipment")]
        public Equipment MaterialName
        {
            get { return fMaterialName; }
            set { SetPropertyValue<Equipment>(nameof(MaterialName), ref fMaterialName, value); }
        }
        int fCounts;
        public int Counts
        {
            get { return fCounts; }
            set { SetPropertyValue<int>(nameof(Counts), ref fCounts, value); }
        }
        DateTime fDeliverDate;
        public DateTime DeliverDate
        {
            get { return fDeliverDate; }
            set { SetPropertyValue<DateTime>(nameof(DeliverDate), ref fDeliverDate, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fComment;
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        MaterialRequest fRequestName;
        [Association(@"MaterialListReferencesMaterialRequest")]
        public MaterialRequest RequestName
        {
            get { return fRequestName; }
            set { SetPropertyValue<MaterialRequest>(nameof(RequestName), ref fRequestName, value); }
        }
    }

}
