//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class MaterialRequest : XPObject
    {
        string fRequestNo;
        public string RequestNo
        {
            get { return fRequestNo; }
            set { SetPropertyValue<string>(nameof(RequestNo), ref fRequestNo, value); }
        }
        DateTime fRequestDate;
        public DateTime RequestDate
        {
            get { return fRequestDate; }
            set { SetPropertyValue<DateTime>(nameof(RequestDate), ref fRequestDate, value); }
        }
        WellWork fWorkID;
        [Association(@"MaterialRequestReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fUserName;
        [Association(@"MaterialRequestReferencesUser")]
        public User UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<User>(nameof(UserName), ref fUserName, value); }
        }
        [Association(@"MaterialListReferencesMaterialRequest"), Aggregated]
        public XPCollection<MaterialList> MaterialLists { get { return GetCollection<MaterialList>(nameof(MaterialLists)); } }
    }

}
