//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Medication : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDose;
        public string Dose
        {
            get { return fDose; }
            set { SetPropertyValue<string>(nameof(Dose), ref fDose, value); }
        }
        string fDrugForm;
        public string DrugForm
        {
            get { return fDrugForm; }
            set { SetPropertyValue<string>(nameof(DrugForm), ref fDrugForm, value); }
        }
        string fCategory;
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>(nameof(Category), ref fCategory, value); }
        }
        bool fAvailForOrder;
        public bool AvailForOrder
        {
            get { return fAvailForOrder; }
            set { SetPropertyValue<bool>(nameof(AvailForOrder), ref fAvailForOrder, value); }
        }
        string fDiscription;
        public string Discription
        {
            get { return fDiscription; }
            set { SetPropertyValue<string>(nameof(Discription), ref fDiscription, value); }
        }
        int fMinCount;
        public int MinCount
        {
            get { return fMinCount; }
            set { SetPropertyValue<int>(nameof(MinCount), ref fMinCount, value); }
        }
        [Association(@"MedicationStockReferencesMedication"), Aggregated]
        public XPCollection<MedicationStock> MedicationStocks { get { return GetCollection<MedicationStock>(nameof(MedicationStocks)); } }
        [Association(@"UsedMedicineReferencesMedication"), Aggregated]
        public XPCollection<UsedMedicine> UsedMedicines { get { return GetCollection<UsedMedicine>(nameof(UsedMedicines)); } }
        [Association(@"DisposedMedicineReferencesMedication"), Aggregated]
        public XPCollection<DisposedMedicine> DisposedMedicines { get { return GetCollection<DisposedMedicine>(nameof(DisposedMedicines)); } }
    }

}
