//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class MedicalReferral : XPObject
    {
        MedicalVisit fMedicalVisit;
        [Association(@"MedicalReferralReferencesMedicalVisit")]
        public MedicalVisit MedicalVisit
        {
            get { return fMedicalVisit; }
            set { SetPropertyValue<MedicalVisit>(nameof(MedicalVisit), ref fMedicalVisit, value); }
        }
        string fSpecialist;
        public string Specialist
        {
            get { return fSpecialist; }
            set { SetPropertyValue<string>(nameof(Specialist), ref fSpecialist, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        DateTime fReturnDate;
        public DateTime ReturnDate
        {
            get { return fReturnDate; }
            set { SetPropertyValue<DateTime>(nameof(ReturnDate), ref fReturnDate, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
