//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class MedicalVisit : XPObject
    {
        Personnel fPatient;
        [Association(@"MedicalVisitReferencesPersonnel")]
        public Personnel Patient
        {
            get { return fPatient; }
            set { SetPropertyValue<Personnel>(nameof(Patient), ref fPatient, value); }
        }
        DateTime fVisitDate;
        public DateTime VisitDate
        {
            get { return fVisitDate; }
            set { SetPropertyValue<DateTime>(nameof(VisitDate), ref fVisitDate, value); }
        }
        string fVisitType;
        public string VisitType
        {
            get { return fVisitType; }
            set { SetPropertyValue<string>(nameof(VisitType), ref fVisitType, value); }
        }
        string fCategory;
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>(nameof(Category), ref fCategory, value); }
        }
        string fSymptoms;
        [Size(SizeAttribute.Unlimited)]
        public string Symptoms
        {
            get { return fSymptoms; }
            set { SetPropertyValue<string>(nameof(Symptoms), ref fSymptoms, value); }
        }
        string fDiagnose;
        public string Diagnose
        {
            get { return fDiagnose; }
            set { SetPropertyValue<string>(nameof(Diagnose), ref fDiagnose, value); }
        }
        User fDoctorName;
        public User DoctorName
        {
            get { return fDoctorName; }
            set { SetPropertyValue<User>(nameof(DoctorName), ref fDoctorName, value); }
        }
        Rig fRigNo;
        [Association(@"MedicalVisitReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        short? fLWD;
        public short? LWD
        {
            get { return fLWD; }
            set { SetPropertyValue<short?>(nameof(LWD), ref fLWD, value); }
        }
        [Association(@"ReportReferencesPatient")]
        public XPCollection<Report> Reports { get { return GetCollection<Report>(nameof(Reports)); } }
        [Association(@"UsedMedicineReferencesPatient"), Aggregated]
        public XPCollection<UsedMedicine> UsedMedicines { get { return GetCollection<UsedMedicine>(nameof(UsedMedicines)); } }
        [Association(@"MedicalReferralReferencesMedicalVisit"), Aggregated]
        public XPCollection<MedicalReferral> MedicalReferrals { get { return GetCollection<MedicalReferral>(nameof(MedicalReferrals)); } }
    }

}
