//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class MedicationStock : XPObject
    {
        Medication fMedicName;
        [Association(@"MedicationStockReferencesMedication")]
        public Medication MedicName
        {
            get { return fMedicName; }
            set { SetPropertyValue<Medication>(nameof(MedicName), ref fMedicName, value); }
        }
        Rig fRigNo;
        [Association(@"MedicationStockReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
        short fAvailCount;
        public short AvailCount
        {
            get { return fAvailCount; }
            set { SetPropertyValue<short>(nameof(AvailCount), ref fAvailCount, value); }
        }
        DateTime fExpDate;
        public DateTime ExpDate
        {
            get { return fExpDate; }
            set { SetPropertyValue<DateTime>(nameof(ExpDate), ref fExpDate, value); }
        }
    }

}
