//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Permit : XPObject
    {
        string fArchiveNo;
        public string ArchiveNo
        {
            get { return fArchiveNo; }
            set { SetPropertyValue<string>(nameof(ArchiveNo), ref fArchiveNo, value); }
        }
        string fPermitType;
        public string PermitType
        {
            get { return fPermitType; }
            set { SetPropertyValue<string>(nameof(PermitType), ref fPermitType, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        DateTime fStartTime;
        public DateTime StartTime
        {
            get { return fStartTime; }
            set { SetPropertyValue<DateTime>(nameof(StartTime), ref fStartTime, value); }
        }
        DateTime? fEndTime;
        public DateTime? EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue<DateTime?>(nameof(EndTime), ref fEndTime, value); }
        }
        Personnel fHolder;
        [Association(@"PermitReferencesPersonnel")]
        public Personnel Holder
        {
            get { return fHolder; }
            set { SetPropertyValue<Personnel>(nameof(Holder), ref fHolder, value); }
        }
        Personnel fResponsible;
        [Association(@"PermitReferencesPersonnel1")]
        public Personnel Responsible
        {
            get { return fResponsible; }
            set { SetPropertyValue<Personnel>(nameof(Responsible), ref fResponsible, value); }
        }
        Personnel fApprover;
        [Association(@"PermitReferencesPersonnel2")]
        public Personnel Approver
        {
            get { return fApprover; }
            set { SetPropertyValue<Personnel>(nameof(Approver), ref fApprover, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        WellWork fWorkID;
        [Association(@"PermitReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fAgent;
        [Association(@"PermitReferencesUser")]
        public User Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<User>(nameof(Agent), ref fAgent, value); }
        }
    }

}
