//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Personnel : XPObject
    {
        string fPersonnelNum;
        public string PersonnelNum
        {
            get { return fPersonnelNum; }
            set { SetPropertyValue<string>(nameof(PersonnelNum), ref fPersonnelNum, value); }
        }
        string fPersonnelName;
        public string PersonnelName
        {
            get { return fPersonnelName; }
            set { SetPropertyValue<string>(nameof(PersonnelName), ref fPersonnelName, value); }
        }
        string fEnglishName;
        public string EnglishName
        {
            get { return fEnglishName; }
            set { SetPropertyValue<string>(nameof(EnglishName), ref fEnglishName, value); }
        }
        string fCurrentRole;
        public string CurrentRole
        {
            get { return fCurrentRole; }
            set { SetPropertyValue<string>(nameof(CurrentRole), ref fCurrentRole, value); }
        }
        DateTime? fBirthDate;
        public DateTime? BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime?>(nameof(BirthDate), ref fBirthDate, value); }
        }
        bool fMarriage;
        public bool Marriage
        {
            get { return fMarriage; }
            set { SetPropertyValue<bool>(nameof(Marriage), ref fMarriage, value); }
        }
        DateTime? fEmpDate;
        public DateTime? EmpDate
        {
            get { return fEmpDate; }
            set { SetPropertyValue<DateTime?>(nameof(EmpDate), ref fEmpDate, value); }
        }
        string fNationalID;
        public string NationalID
        {
            get { return fNationalID; }
            set { SetPropertyValue<string>(nameof(NationalID), ref fNationalID, value); }
        }
        string fMobileNum;
        public string MobileNum
        {
            get { return fMobileNum; }
            set { SetPropertyValue<string>(nameof(MobileNum), ref fMobileNum, value); }
        }
        string fHomeNum;
        public string HomeNum
        {
            get { return fHomeNum; }
            set { SetPropertyValue<string>(nameof(HomeNum), ref fHomeNum, value); }
        }
        string fInsuranceNum;
        public string InsuranceNum
        {
            get { return fInsuranceNum; }
            set { SetPropertyValue<string>(nameof(InsuranceNum), ref fInsuranceNum, value); }
        }
        string fAddress;
        [Size(SizeAttribute.Unlimited)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fPreviousRole;
        public string PreviousRole
        {
            get { return fPreviousRole; }
            set { SetPropertyValue<string>(nameof(PreviousRole), ref fPreviousRole, value); }
        }
        DateTime? fLastUpgradeDate;
        public DateTime? LastUpgradeDate
        {
            get { return fLastUpgradeDate; }
            set { SetPropertyValue<DateTime?>(nameof(LastUpgradeDate), ref fLastUpgradeDate, value); }
        }
        string fShoeSize;
        public string ShoeSize
        {
            get { return fShoeSize; }
            set { SetPropertyValue<string>(nameof(ShoeSize), ref fShoeSize, value); }
        }
        string fClothSize;
        public string ClothSize
        {
            get { return fClothSize; }
            set { SetPropertyValue<string>(nameof(ClothSize), ref fClothSize, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        DateTime? fLicenseDate;
        public DateTime? LicenseDate
        {
            get { return fLicenseDate; }
            set { SetPropertyValue<DateTime?>(nameof(LicenseDate), ref fLicenseDate, value); }
        }
        string fBusinessEmail;
        public string BusinessEmail
        {
            get { return fBusinessEmail; }
            set { SetPropertyValue<string>(nameof(BusinessEmail), ref fBusinessEmail, value); }
        }
        Rig fActiveRig;
        [Association(@"PersonnelReferencesRig")]
        public Rig ActiveRig
        {
            get { return fActiveRig; }
            set { SetPropertyValue<Rig>(nameof(ActiveRig), ref fActiveRig, value); }
        }
        [Association(@"TrainingReferencesPersonnel")]
        public XPCollection<Training> Trainings { get { return GetCollection<Training>(nameof(Trainings)); } }
        [Association(@"CommitteeReferencesParticipants")]
        public XPCollection<Committee> Committees { get { return GetCollection<Committee>(nameof(Committees)); } }
        [Association(@"PersonnelReferencesPractice")]
        public XPCollection<Practice> Practices { get { return GetCollection<Practice>(nameof(Practices)); } }
        [Association(@"VehicleReferencesPersonnel")]
        public XPCollection<Vehicle> Vehicles { get { return GetCollection<Vehicle>(nameof(Vehicles)); } }
        [Association(@"CommitteeReferencesChief")]
        public XPCollection<Committee> CommitteesChief { get { return GetCollection<Committee>(nameof(CommitteesChief)); } }
        [Association(@"StopCardsReferencesPersonnel")]
        public XPCollection<StopCard> StopCardsReports { get { return GetCollection<StopCard>(nameof(StopCardsReports)); } }
        [Association(@"WarningsReferencesPersonnel"), Aggregated]
        public XPCollection<Warning> Warnings { get { return GetCollection<Warning>(nameof(Warnings)); } }
        [Association(@"IncentiveReferencesPersonnel"), Aggregated]
        public XPCollection<Incentive> Incentives { get { return GetCollection<Incentive>(nameof(Incentives)); } }
        [Association(@"PPEReferencesPersonnel"), Aggregated]
        public XPCollection<PPE> PPEs { get { return GetCollection<PPE>(nameof(PPEs)); } }
        [Association(@"AccidentReportReferencesPersonnel"), Aggregated]
        public XPCollection<AccidentReport> Accidents { get { return GetCollection<AccidentReport>(nameof(Accidents)); } }
        [Association(@"MedicalVisitReferencesPersonnel"), Aggregated]
        public XPCollection<MedicalVisit> MedicalVisits { get { return GetCollection<MedicalVisit>(nameof(MedicalVisits)); } }
    }

}
