//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class PPE : XPObject
    {
        Equipment fEquipmentName;
        [Association(@"PPEReferencesEquipment")]
        public Equipment EquipmentName
        {
            get { return fEquipmentName; }
            set { SetPropertyValue<Equipment>(nameof(EquipmentName), ref fEquipmentName, value); }
        }
        Personnel fPersonnelName;
        [Association(@"PPEReferencesPersonnel")]
        public Personnel PersonnelName
        {
            get { return fPersonnelName; }
            set { SetPropertyValue<Personnel>(nameof(PersonnelName), ref fPersonnelName, value); }
        }
        DateTime fDeliverDate;
        public DateTime DeliverDate
        {
            get { return fDeliverDate; }
            set { SetPropertyValue<DateTime>(nameof(DeliverDate), ref fDeliverDate, value); }
        }
        User fAgent;
        [Association(@"PPEReferencesUser")]
        public User Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<User>(nameof(Agent), ref fAgent, value); }
        }
    }

}
