//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class PracticeCons : XPObject
    {
        Practice fPractice;
        [Association(@"PracticeConsReferencesPractice")]
        public Practice Practice
        {
            get { return fPractice; }
            set { SetPropertyValue<Practice>(nameof(Practice), ref fPractice, value); }
        }
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fAdjustment;
        [Size(SizeAttribute.Unlimited)]
        public string Adjustment
        {
            get { return fAdjustment; }
            set { SetPropertyValue<string>(nameof(Adjustment), ref fAdjustment, value); }
        }
        string fTrackerRole;
        public string TrackerRole
        {
            get { return fTrackerRole; }
            set { SetPropertyValue<string>(nameof(TrackerRole), ref fTrackerRole, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
    }

}
