//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Practice : XPObject
    {
        string fDrillType;
        public string DrillType
        {
            get { return fDrillType; }
            set { SetPropertyValue<string>(nameof(DrillType), ref fDrillType, value); }
        }
        DateTime fHoldDate;
        public DateTime HoldDate
        {
            get { return fHoldDate; }
            set { SetPropertyValue<DateTime>(nameof(HoldDate), ref fHoldDate, value); }
        }
        string fPlace;
        public string Place
        {
            get { return fPlace; }
            set { SetPropertyValue<string>(nameof(Place), ref fPlace, value); }
        }
        WellWork fWorkID;
        [Association(@"PracticeReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fAgent;
        [Association(@"PracticeReferencesUser")]
        public User Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<User>(nameof(Agent), ref fAgent, value); }
        }
        [Association(@"PersonnelReferencesPractice")]
        public XPCollection<Personnel> Personnels { get { return GetCollection<Personnel>(nameof(Personnels)); } }
        [Association(@"PracticePronsReferencesPractice"), Aggregated]
        public XPCollection<PracticeProns> PracticePronsCollection { get { return GetCollection<PracticeProns>(nameof(PracticePronsCollection)); } }
        [Association(@"PracticeConsReferencesPractice"), Aggregated]
        public XPCollection<PracticeCons> PracticeConsCollection { get { return GetCollection<PracticeCons>(nameof(PracticeConsCollection)); } }
    }

}
