//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Project : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        DateTime? fStartDate;
        public DateTime? StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime?>(nameof(StartDate), ref fStartDate, value); }
        }
        DateTime? fEndDate;
        public DateTime? EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime?>(nameof(EndDate), ref fEndDate, value); }
        }
        [Association(@"WellReferencesProject"), Aggregated]
        public XPCollection<Well> Wells { get { return GetCollection<Well>(nameof(Wells)); } }
    }

}
