//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Report : XPObject
    {
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        DateTime fSubDate;
        public DateTime SubDate
        {
            get { return fSubDate; }
            set { SetPropertyValue<DateTime>(nameof(SubDate), ref fSubDate, value); }
        }
        HSEForm fForm;
        [Association(@"ReportReferencesHSEForm")]
        public HSEForm Form
        {
            get { return fForm; }
            set { SetPropertyValue<HSEForm>(nameof(Form), ref fForm, value); }
        }
        byte[] fFormData;
        [MemberDesignTimeVisibility(true)]
        public byte[] FormData
        {
            get { return fFormData; }
            set { SetPropertyValue<byte[]>(nameof(FormData), ref fFormData, value); }
        }
        User fUserName;
        [Association(@"ReportReferencesUser2")]
        public User UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<User>(nameof(UserName), ref fUserName, value); }
        }
        WellWork fWorkID;
        [Association(@"ReportReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        [Association(@"ReportReferencesUser")]
        public XPCollection<User> RecieverUsers { get { return GetCollection<User>(nameof(RecieverUsers)); } }
        [Association(@"ReportReferencesUser1")]
        public XPCollection<User> ReadedUsers { get { return GetCollection<User>(nameof(ReadedUsers)); } }
        [Association(@"ReportReferencesPatient")]
        public XPCollection<MedicalVisit> Visits { get { return GetCollection<MedicalVisit>(nameof(Visits)); } }
    }

}
