//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Rig : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"RigReferencesUser")]
        public XPCollection<User> Users { get { return GetCollection<User>(nameof(Users)); } }
        [Association(@"PersonnelReferencesRig")]
        public XPCollection<Personnel> Personnels { get { return GetCollection<Personnel>(nameof(Personnels)); } }
        [Association(@"MedicationStockReferencesRig"), Aggregated]
        public XPCollection<MedicationStock> MedicationStocks { get { return GetCollection<MedicationStock>(nameof(MedicationStocks)); } }
        [Association(@"DisposedMedicineReferencesRig"), Aggregated]
        public XPCollection<DisposedMedicine> DisposedMedicines { get { return GetCollection<DisposedMedicine>(nameof(DisposedMedicines)); } }
        [Association(@"WellWorkReferencesRig"), Aggregated]
        public XPCollection<WellWork> WellWorks { get { return GetCollection<WellWork>(nameof(WellWorks)); } }
        [Association(@"EquipmentStockReferencesRig"), Aggregated]
        public XPCollection<EquipmentStock> EquipmentStocks { get { return GetCollection<EquipmentStock>(nameof(EquipmentStocks)); } }
        [Association(@"FireEquipReferencesRig"), Aggregated]
        public XPCollection<FireEquip> FireEquips { get { return GetCollection<FireEquip>(nameof(FireEquips)); } }
        [Association(@"AssetReferencesRig"), Aggregated]
        public XPCollection<Asset> Assets { get { return GetCollection<Asset>(nameof(Assets)); } }
        [Association(@"VehicleReferencesRig"), Aggregated]
        public XPCollection<Vehicle> Vehicles { get { return GetCollection<Vehicle>(nameof(Vehicles)); } }
        [Association(@"MedicalVisitReferencesRig"), Aggregated]
        public XPCollection<MedicalVisit> MedicalVisits { get { return GetCollection<MedicalVisit>(nameof(MedicalVisits)); } }
    }

}
