//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class StopCard : XPObject
    {
        DateTime? fReportDate;
        public DateTime? ReportDate
        {
            get { return fReportDate; }
            set { SetPropertyValue<DateTime?>(nameof(ReportDate), ref fReportDate, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        string fCategory;
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>(nameof(Category), ref fCategory, value); }
        }
        string fObservation;
        [Size(SizeAttribute.Unlimited)]
        public string Observation
        {
            get { return fObservation; }
            set { SetPropertyValue<string>(nameof(Observation), ref fObservation, value); }
        }
        string fResponsible;
        public string Responsible
        {
            get { return fResponsible; }
            set { SetPropertyValue<string>(nameof(Responsible), ref fResponsible, value); }
        }
        Personnel fReporter;
        [Association(@"StopCardsReferencesPersonnel")]
        public Personnel Reporter
        {
            get { return fReporter; }
            set { SetPropertyValue<Personnel>(nameof(Reporter), ref fReporter, value); }
        }
        string fSeverity;
        public string Severity
        {
            get { return fSeverity; }
            set { SetPropertyValue<string>(nameof(Severity), ref fSeverity, value); }
        }
        string fActions;
        [Size(SizeAttribute.Unlimited)]
        public string Actions
        {
            get { return fActions; }
            set { SetPropertyValue<string>(nameof(Actions), ref fActions, value); }
        }
        string fStatus;
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fComments;
        [Size(SizeAttribute.Unlimited)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>(nameof(Comments), ref fComments, value); }
        }
        WellWork fWorkID;
        [Association(@"StopCardsReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fAgent;
        [Association(@"StopCardsReferencesUser")]
        public User Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<User>(nameof(Agent), ref fAgent, value); }
        }
        bool fIsApproved;
        public bool IsApproved
        {
            get { return fIsApproved; }
            set { SetPropertyValue<bool>(nameof(IsApproved), ref fIsApproved, value); }
        }
        int fScore;
        public int Score
        {
            get { return fScore; }
            set { SetPropertyValue<int>(nameof(Score), ref fScore, value); }
        }
        string fProbablety;
        public string Probablety
        {
            get { return fProbablety; }
            set { SetPropertyValue<string>(nameof(Probablety), ref fProbablety, value); }
        }
        string fEfficiency;
        [Size(SizeAttribute.Unlimited)]
        public string Efficiency
        {
            get { return fEfficiency; }
            set { SetPropertyValue<string>(nameof(Efficiency), ref fEfficiency, value); }
        }
    }

}
