//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Training : XPObject
    {
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        User fTrainer;
        [Association(@"TrainingReferencesUser1")]
        public User Trainer
        {
            get { return fTrainer; }
            set { SetPropertyValue<User>(nameof(Trainer), ref fTrainer, value); }
        }
        DateTime fHoldDate;
        public DateTime HoldDate
        {
            get { return fHoldDate; }
            set { SetPropertyValue<DateTime>(nameof(HoldDate), ref fHoldDate, value); }
        }
        int fDuration;
        public int Duration
        {
            get { return fDuration; }
            set { SetPropertyValue<int>(nameof(Duration), ref fDuration, value); }
        }
        WellWork fWorkID;
        [Association(@"TrainingReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fAgent;
        [Association(@"TrainingReferencesUser")]
        public User Agent
        {
            get { return fAgent; }
            set { SetPropertyValue<User>(nameof(Agent), ref fAgent, value); }
        }
        [Association(@"TrainingReferencesPersonnel")]
        public XPCollection<Personnel> Personnels { get { return GetCollection<Personnel>(nameof(Personnels)); } }
    }

}
