//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class UsedMedicine : XPObject
    {
        Medication fMedicName;
        [Association(@"UsedMedicineReferencesMedication")]
        public Medication MedicName
        {
            get { return fMedicName; }
            set { SetPropertyValue<Medication>(nameof(MedicName), ref fMedicName, value); }
        }
        MedicalVisit fPatientName;
        [Association(@"UsedMedicineReferencesPatient")]
        public MedicalVisit PatientName
        {
            get { return fPatientName; }
            set { SetPropertyValue<MedicalVisit>(nameof(PatientName), ref fPatientName, value); }
        }
        short fMedCount;
        public short MedCount
        {
            get { return fMedCount; }
            set { SetPropertyValue<short>(nameof(MedCount), ref fMedCount, value); }
        }
    }

}
