//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class User : Personnel
    {
        string fUsername;
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fPassword;
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fSiteRole;
        public string SiteRole
        {
            get { return fSiteRole; }
            set { SetPropertyValue<string>(nameof(SiteRole), ref fSiteRole, value); }
        }
        DateTime? fLastLogin;
        public DateTime? LastLogin
        {
            get { return fLastLogin; }
            set { SetPropertyValue<DateTime?>(nameof(LastLogin), ref fLastLogin, value); }
        }
        string fDashboardId;
        public string DashboardId
        {
            get { return fDashboardId; }
            set { SetPropertyValue<string>(nameof(DashboardId), ref fDashboardId, value); }
        }
        [Association(@"ReportReferencesUser")]
        public XPCollection<Report> RecievedReports { get { return GetCollection<Report>(nameof(RecievedReports)); } }
        [Association(@"ReportReferencesUser1")]
        public XPCollection<Report> ReadedReports { get { return GetCollection<Report>(nameof(ReadedReports)); } }
        [Association(@"RigReferencesUser")]
        public XPCollection<Rig> Rigs { get { return GetCollection<Rig>(nameof(Rigs)); } }
        [Association(@"MaterialRequestReferencesUser")]
        public XPCollection<MaterialRequest> MaterialRequests { get { return GetCollection<MaterialRequest>(nameof(MaterialRequests)); } }
        [Association(@"PPEReferencesUser")]
        public XPCollection<PPE> HandedPPEs { get { return GetCollection<PPE>(nameof(HandedPPEs)); } }
        [Association(@"WarningReferencesUser")]
        public XPCollection<Warning> IssuedWarnings { get { return GetCollection<Warning>(nameof(IssuedWarnings)); } }
        [Association(@"IncentiveReferencesUser")]
        public XPCollection<Incentive> IssuedIncentives { get { return GetCollection<Incentive>(nameof(IssuedIncentives)); } }
        [Association(@"ReportReferencesUser2")]
        public XPCollection<Report> Reports { get { return GetCollection<Report>(nameof(Reports)); } }
        [Association(@"CommitteeReferencesUser")]
        public XPCollection<Committee> CommitteesSecretary { get { return GetCollection<Committee>(nameof(CommitteesSecretary)); } }
        [Association(@"PracticeReferencesUser")]
        public XPCollection<Practice> PracticesHold { get { return GetCollection<Practice>(nameof(PracticesHold)); } }
        [Association(@"TrainingReferencesUser")]
        public XPCollection<Training> CourseAgent { get { return GetCollection<Training>(nameof(CourseAgent)); } }
        [Association(@"TrainingReferencesUser1")]
        public XPCollection<Training> CourseTeacher { get { return GetCollection<Training>(nameof(CourseTeacher)); } }
        [Association(@"AccidentReportReferencesUser")]
        public XPCollection<AccidentReport> AccidentReports { get { return GetCollection<AccidentReport>(nameof(AccidentReports)); } }
        [Association(@"StopCardsReferencesUser")]
        public XPCollection<StopCard> StopCardsCollection { get { return GetCollection<StopCard>(nameof(StopCardsCollection)); } }
        [Association(@"PermitReferencesUser")]
        public XPCollection<Permit> Permits { get { return GetCollection<Permit>(nameof(Permits)); } }
    }

}
