//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Vehicle : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fPlateNo;
        public string PlateNo
        {
            get { return fPlateNo; }
            set { SetPropertyValue<string>(nameof(PlateNo), ref fPlateNo, value); }
        }
        DateTime fLastCheckDate;
        public DateTime LastCheckDate
        {
            get { return fLastCheckDate; }
            set { SetPropertyValue<DateTime>(nameof(LastCheckDate), ref fLastCheckDate, value); }
        }
        short fProdDate;
        public short ProdDate
        {
            get { return fProdDate; }
            set { SetPropertyValue<short>(nameof(ProdDate), ref fProdDate, value); }
        }
        DateTime? fInsuranceDate;
        public DateTime? InsuranceDate
        {
            get { return fInsuranceDate; }
            set { SetPropertyValue<DateTime?>(nameof(InsuranceDate), ref fInsuranceDate, value); }
        }
        Personnel fDriver;
        [Association(@"VehicleReferencesPersonnel")]
        public Personnel Driver
        {
            get { return fDriver; }
            set { SetPropertyValue<Personnel>(nameof(Driver), ref fDriver, value); }
        }
        Rig fRigNo;
        [Association(@"VehicleReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
    }

}
