//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Warning : XPObject
    {
        Personnel fPersonnelName;
        [Association(@"WarningsReferencesPersonnel")]
        public Personnel PersonnelName
        {
            get { return fPersonnelName; }
            set { SetPropertyValue<Personnel>(nameof(PersonnelName), ref fPersonnelName, value); }
        }
        DateTime fIssueDate;
        public DateTime IssueDate
        {
            get { return fIssueDate; }
            set { SetPropertyValue<DateTime>(nameof(IssueDate), ref fIssueDate, value); }
        }
        string fReason;
        public string Reason
        {
            get { return fReason; }
            set { SetPropertyValue<string>(nameof(Reason), ref fReason, value); }
        }
        WellWork fWorkID;
        [Association(@"WarningsReferencesWellWork")]
        public WellWork WorkID
        {
            get { return fWorkID; }
            set { SetPropertyValue<WellWork>(nameof(WorkID), ref fWorkID, value); }
        }
        User fIssuer;
        [Association(@"WarningReferencesUser")]
        public User Issuer
        {
            get { return fIssuer; }
            set { SetPropertyValue<User>(nameof(Issuer), ref fIssuer, value); }
        }
    }

}
