//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class Well : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>(nameof(Location), ref fLocation, value); }
        }
        Project fProjectName;
        [Association(@"WellReferencesProject")]
        public Project ProjectName
        {
            get { return fProjectName; }
            set { SetPropertyValue<Project>(nameof(ProjectName), ref fProjectName, value); }
        }
        [Association(@"WellWorkReferencesWell"), Aggregated]
        public XPCollection<WellWork> WellWorks { get { return GetCollection<WellWork>(nameof(WellWorks)); } }
    }

}
