//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Samco_HSE.HSEData
{

    public partial class WellWork : XPObject
    {
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>(nameof(StartDate), ref fStartDate, value); }
        }
        DateTime? fEndDate;
        public DateTime? EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime?>(nameof(EndDate), ref fEndDate, value); }
        }
        Well fWellNo;
        [Association(@"WellWorkReferencesWell")]
        public Well WellNo
        {
            get { return fWellNo; }
            set { SetPropertyValue<Well>(nameof(WellNo), ref fWellNo, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        Rig fRigNo;
        [Association(@"WellWorkReferencesRig")]
        public Rig RigNo
        {
            get { return fRigNo; }
            set { SetPropertyValue<Rig>(nameof(RigNo), ref fRigNo, value); }
        }
        [Association(@"IncentiveReferencesWellWork")]
        public XPCollection<Incentive> Incentives { get { return GetCollection<Incentive>(nameof(Incentives)); } }
        [Association(@"StopCardsReferencesWellWork")]
        public XPCollection<StopCard> StopCards { get { return GetCollection<StopCard>(nameof(StopCards)); } }
        [Association(@"MaterialRequestReferencesWellWork"), Aggregated]
        public XPCollection<MaterialRequest> MaterialRequests { get { return GetCollection<MaterialRequest>(nameof(MaterialRequests)); } }
        [Association(@"WarningsReferencesWellWork"), Aggregated]
        public XPCollection<Warning> Warnings { get { return GetCollection<Warning>(nameof(Warnings)); } }
        [Association(@"CommitteeReferencesWellWork"), Aggregated]
        public XPCollection<Committee> Committees { get { return GetCollection<Committee>(nameof(Committees)); } }
        [Association(@"PracticeReferencesWellWork"), Aggregated]
        public XPCollection<Practice> Practices { get { return GetCollection<Practice>(nameof(Practices)); } }
        [Association(@"AccidentReportReferencesWellWork"), Aggregated]
        public XPCollection<AccidentReport> AccidentReports { get { return GetCollection<AccidentReport>(nameof(AccidentReports)); } }
        [Association(@"ReportReferencesWellWork"), Aggregated]
        public XPCollection<Report> Reports { get { return GetCollection<Report>(nameof(Reports)); } }
        [Association(@"TrainingReferencesWellWork"), Aggregated]
        public XPCollection<Training> Trainings { get { return GetCollection<Training>(nameof(Trainings)); } }
    }

}
